project.name: queue-multiple-consumer

server.port: 8090
management.port: 8091

logging.path: /app/cypher/log

spring:
  application:
    name: queue-multiple-consumer
  rabbitmq:
    addresses: localhost
    virtual_host: xmen

  cloud.stream:
    bindings:
      #Fila aplicação externa
      FilaUnicaOutput:
        destination: ${project.name}.FilaUnica

      #Consumidores da mesma fila
      FilaUnicaInputCypher:
        destination: ${project.name}.FilaUnica
        group: criarFatura
        consumer:
          maxAttempts: 5
      FilaUnicaInputJuggernaut:
        destination: ${project.name}.FilaUnica
        group: criarFatura
        consumer:
          maxAttempts: 5

    rabbit.bindings:
      #IN CYPHER
      FilaUnicaInputCypher:
        consumer:
          requestHeaderPatterns:
            tenant: "cypher"
      #IN JUGG
      FilaUnicaInputJuggernaut:
        consumer:
          requestHeaderPatterns:
            tenant: "juggernaut"