project.name: cypher

logging.path: /app/cypher/log

spring:
  application:
    name: queue-multiple-consumer
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}
    virtual_host: xmen

  cloud.stream:
    bindings:
      #Filas Cypher
      FaturaConvertidaOutput:
        destination: ${project.name}.FaturaConvertida
      FaturaConvertidaInput:
        destination: ${project.name}.FaturaConvertida
        group: criarFatura
        consumer:
          maxAttempts: 5

    rabbit.bindings:
      FaturaConvertidaInput:
        consumer:
          autoBindDlq: true
          republishToDlq: true