spring:
  application.name: producer-xmen
  rabbitmq:
    addresses: localhost
    virtual_host: xmen

  cloud:
    stream.bindings:
      XMenQueueOutput:
        destination: magneto.faturaProcessada