#mvn dependency:resolve -Dclassifier=javadoc
#mvn dependency:sources

spring:
  application.name: producer-xmen
  rabbitmq:
    addresses: localhost
    virtual_host: xmen

  cloud:
    stream.bindings:
      XMenQueueOutput:
        destination: xmen-queue
        producer:
          requiredGroups: xmen-group

    rabbit.bindings:
        XMenQueueOutput:
          producer:
            bindQueue: false