#docker-compose -f postgres_rabbit_docker-compose.yml up -d --force-recreate
version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_VHOST=xmen
