server:
  port: 8083

spring:
  application.name: consumer-xmen
  rabbitmq:
    addresses: localhost
    virtual_host: xmen

  cloud:
    stream.bindings:
      XMenConsumerQueueInput:
        destination: juggernaut-destination
        group: xmen-group

    rabbit.bindings:
      XMenConsumerQueueInput:
        consumer:
          durableSubscription: true