project.name: cypher

server.port: 8083

spring:
  application.name: consumer-xmen
  rabbitmq:
    addresses: localhost
    virtual_host: xmen

  cloud:
    stream.bindings:
      XMenConsumerQueueInput:
        destination: magneto.faturaProcessada.${project.name}
        group: invoiceProcessed

    rabbit.bindings:
      XMenConsumerQueueInput:
        consumer:
          durableSubscription: true